### ISSUE TITLE
Large cwltool output can cause OutofMemoryError

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1420]
## Bug Report

Large output from cwltool (as opposed to stdout/stderr from the workflow itself) can cause an OutOfMemory. In this case, 2.2GB of it.

```
[job cgp_irap.cwl] completed success
Final process status is success
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
    at java.lang.StringCoding.encode(StringCoding.java:350)
    at java.lang.String.getBytes(String.java:941)
    at org.apache.commons.io.IOUtils.write(IOUtils.java:1857)
    at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1982)
    at io.github.collaboratory.LauncherCWL.outputIntegrationOutput(LauncherCWL.java:152)
    at io.github.collaboratory.LauncherCWL.runCWLCommand(LauncherCWL.java:605)
    at io.github.collaboratory.LauncherCWL.run(LauncherCWL.java:224)
    at io.dockstore.client.cli.nested.AbstractEntryClient.handleCWLLaunch(AbstractEntryClient.java:1139)
    at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:1073)
    at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:1061)
    at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:1035)
    at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:252)
    at io.dockstore.client.cli.Client.run(Client.java:689)
    at io.dockstore.client.cli.Client.main(Client.java:602)
```

https://gitter.im/ga4gh/dockstore?at=5af594dfe0b50c2d05b4aaa8

This can probably be made more efficient by streaming the output. 

Encountered by @byb121 see https://gitter.im/ga4gh/dockstore?at=5af594dfe0b50c2d05b4aaa8 and https://gitter.im/ga4gh/dockstore?at=5afa9447d332ee5fad1c46e4

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-165)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6.x
┆Sprint: Seabright Sprint 9 Ice Boat
┆Issue Number: DOCK-165

**Comment by denis-yuen** [comment]
Somewhat related issue. 
Are we properly displaying stdout and stderr when calling out to cwltool for commands like convert? 
https://gitter.im/ga4gh/dockstore?at=5afc78a09ad18967b9eef0b1

**Comment by denis-yuen** [comment]
For the second issue, this works with 1.4.1 and develop, so it might just be an older Dockstore CLI. 
Should see something like 
```
$ dockstore workflow convert entry2json --entry github.com/NCI-GDC/gdc-dnaseq-cwl/GDC_DNASeq:master
problems running command: cwltool --non-strict --print-pre /tmp/1526569263798-0/workflows/dnaseq/transform.cwl
stderr for command:
	Traceback (most recent call last):
	  File "/usr/local/bin/cwltool", line 7, in <module>
	    from cwltool.main import main
	  File "/usr/local/lib/python2.7/dist-packages/cwltool/main.py", line 22, in <module>
	    import schema_salad.validate as validate
	ImportError: No module named schema_salad.validate
	
java.lang.RuntimeException: problems running command: cwltool --non-strict --print-pre /tmp/1526569263798-0/workflows/dnaseq/transform.cwl
	at io.cwl.avro.Utilities.executeCommand(Utilities.java:96)
	at io.cwl.avro.CWL.parseCWL(CWL.java:494)
	at io.github.collaboratory.cwl.CWLClient.generateInputJson(CWLClient.java:325)
	at io.dockstore.client.cli.nested.WorkflowClient.convertWorkflow2Json(WorkflowClient.java:291)
	at io.dockstore.client.cli.nested.WorkflowClient.handleEntry2json(WorkflowClient.java:251)
	at io.dockstore.client.cli.nested.AbstractEntryClient.convert(AbstractEntryClient.java:512)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:217)
	at io.dockstore.client.cli.Client.run(Client.java:695)
	at io.dockstore.client.cli.Client.main(Client.java:606)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: cwltool --non-strict --print-pre /tmp/1526569263798-0/workflows/dnaseq/transform.cwl (Exit value: 1)
	at io.cwl.avro.Utilities.executeCommand(Utilities.java:92)
	... 8 more
```

**Comment by cricketsloan** [comment]
➤ Denis Yuen commented:

Present at https://beta.docs.dockstore.org/en/develop/advanced-topics/advanced-features.html ( https://beta.docs.dockstore.org/en/develop/advanced-topics/advanced-features.html )
