### ISSUE TITLE
CLI should have/surface error message if Docker is not running

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2082]
### Desired behaviour
Currently CLI will fail if Docker is needed for a workflow, but not running. There is no error message indicating this is the problem. Cromwell engine potentially outputs a related error message that shows when running Cromwell manually, but Dockstore CLI doesn't surface this to the user. This feature is more relevant for users who need to manually start up Docker, like in Docker Desktop for Mac.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-239)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 13 Motorboat
┆Issue Number: DOCK-239

**Comment by denis-yuen** [comment]
Implementor can consider tackling at the same time as #1876

**Comment by cricketsloan** [comment]
Is this is issue that came from Vincent?

Hi -- I had the misfortune of attempting to use the CLI when my docker
desktop had died.  The error messages were not particularly helpful and only
when I tried to use cromwell manually did I come to an understanding
of the situation.  Perhaps the CLI could check for running docker and
fail with a clear message if such is not found?

dockstore workflow launch --entry github.com/vjcitn/dsdemo:master --json dsdemoInputs.json

Downloading Dockstore to /Users/stvjc/.dockstore/self-installs/dockstore-client-1.6.0-alpha.5.jar now...

https://github.com/ga4gh/dockstore/releases/download/1.6.0-alpha.5/dockstore-client-1.6.0-alpha.5-shaded.jar

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

Dload  Upload   Total   Spent    Left  Speed

100   631    0   631    0     0   1561      0 --:--:-- --:--:-- --:--:--  1565

100 46.2M  100 46.2M    0     0  1853k      0  0:00:25  0:00:25 --:--:-- 1253k

Creating directories for run of Dockstore launcher in current working directory: /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/1549206345936-0

Provisioning your input files to your local machine

Calling out to Cromwell to run your workflow

java jar /Users/stvjc/.dockstore/libraries/cromwell36.jar run /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/1549206345936-0/run1.wdl --inputs /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/foo1724821479851536343json

org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)

at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)

at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)

at java.lang.Thread.run(Thread.java:745)

10:06:30.640 [main] ERROR io.github.collaboratory.wdl.WDLClient - Problem running cromwell: 

java.lang.RuntimeException: problems running command: java jar /Users/stvjc/.dockstore/libraries/cromwell36.jar run /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/1549206345936-0/run1.wdl --inputs /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/foo1724821479851536343json

at io.dockstore.common.Utilities.executeCommand(Utilities.java:142)

at io.dockstore.common.Utilities.executeCommand(Utilities.java:88)

at io.github.collaboratory.wdl.WDLClient.launch(WDLClient.java:202)

at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:439)

at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:236)

at io.dockstore.client.cli.Client.run(Client.java:706)

at io.dockstore.client.cli.Client.main(Client.java:608)

Caused by: org.apache.commons.exec.ExecuteException: problems running command: java jar /Users/stvjc/.dockstore/libraries/cromwell36.jar run /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/1549206345936-0/run1.wdl --inputs /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/foo1724821479851536343json (Exit value: 1)

at io.dockstore.common.Utilities.executeCommand(Utilities.java:138)

... 6 common frames omitted

Cromwell exit code: 1

10:06:30.661 [main] ERROR io.dockstore.client.cli.ArgumentUtility - org.apache.commons.exec.ExecuteException: problems running command: java jar /Users/stvjc/.dockstore/libraries/cromwell36.jar run /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/1549206345936-0/run1.wdl --inputs /var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/foo1724821479851536343json (Exit value: 1)

at io.github.collaboratory.wdl.WDLClient.launch(WDLClient.java:209)

at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:439)

at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:236)

at io.dockstore.client.cli.Client.run(Client.java:706)

at io.dockstore.client.cli.Client.main(Client.java:608)

**Comment by denis-yuen** [comment]
Punting for now, currently in backlog

**Comment by Ldcabansay** [comment]
Verified on Dockstore 1.7.0-beta.3.  A warning message displays if Docker is not running when launching a workflow with the Dockstore CLI.
