### ISSUE TITLE
Lots of warnings when Dockstore CLI with OpenJDK 11

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2388]
## Bug Report

I get a lot of warnings when running Dockstore 1.6 CLI with OpenJDK 11 on my Ubuntu 16.04 machine. Do not get the warnings with Java 8.

Despite the warnings, it still works (at least the `--version` option does).

### Steps to reproduce the behaviour 
This is partial, there are lots more warnings:
```
coverbeck@coverbeck-XPS-13-9370:~/git/DataBiosphere/terra-ui$ dockstore --version
Dockstore version 1.6.0
You are running the latest stable version...
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
coverbeck@coverbeck-XPS-13-9370:~/git/DataBiosphere/terra-ui$ sudo update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
  3            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 0
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
coverbeck@coverbeck-XPS-13-9370:~/git/DataBiosphere/terra-ui$ dockstore --version
Apr 12, 2019 5:43:53 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2358)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1308)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1304)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1304)
	at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1247)
	at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
	at org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:144)
	at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:178)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:129)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:180)
	at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:740)
	at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:694)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:461)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2288)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:125)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1373)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1368)
	at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1430)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1355)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1344)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:354)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:201)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:221)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1375)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:272)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:366)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:774)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:786)
	at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
	at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:97)
	at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:67)
	at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:698)
	at io.swagger.client.api.UsersApi.getUser(UsersApi.java:429)
	at io.dockstore.client.cli.Client.setupClientEnvironment(Client.java:796)
	at io.dockstore.client.cli.Client.run(Client.java:670)
	at io.dockstore.client.cli.Client.main(Client.java:611)
```
### Environment (Browser or OS and Dockstore version)

* Dockstore 1.6.0
* Ubuntu 16.04.6 LTS

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-680)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 12 Liner
┆Issue Number: DOCK-680

**Comment by garyluu** [comment]
can you type in `java --version`?

**Comment by coverbeck** [comment]
```
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1, mixed mode, sharing)
```

**Comment by garyluu** [comment]
Ok, ya.  I get this too.

**Comment by denis-yuen** [comment]
Clarify:
For Java 8 (with CLI 1.6): this is probably just a FAQ (don't use Java 11)
For Java 11 (with CLI 1.7): pom.xml fix potentially

**Comment by david4096** [comment]
Can confirm I saw this.

**Comment by denis-yuen** [comment]
Need FAQ for 1.6.0 at https://beta.docs.dockstore.org/en/develop/faq.html

Verified fix for CLI

**Comment by denis-yuen** [comment]
Documentation resolved with https://github.com/dockstore/dockstore-documentation/commit/471483f7250179bf6d6734472254403121ac4100
