### ISSUE TITLE
toil FileProvisioning plugin exceptions

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#2473]
Running the latest against staging I got the following error trying to run a CWL workflow using `toil` as the `cwl-runner`. This is toil version 3.19.0 run using `--script`. There are some problems installing the `3.15.0` version that dockstore currently experimentally supports.

```
toil-cwl-runner stdout:
{
    "output_file": {
        "location": "file:///home/david/git/dockstore/datastore/launcher-c2886001-1125-4529-9173-88506a0c73bf/outputs/md5sum.txt",
        "basename": "md5sum.txt",
        "nameroot": "md5sum",
        "nameext": ".txt",
        "class": "File",
        "checksum": "sha1$abb50cf3b742cd06bdaddfc80a26ddf5ec47e993",
        "size": 33,
        "format": "http://edamontology.org/data_3671"
    }
}
toil-cwl-runner stderr:
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/tmp/tmp775j_c2d'.

Saving copy of toil-cwl-runner stdout to: /home/david/git/dockstore/datastore/launcher-c2886001-1125-4529-9173-88506a0c73bf/outputs/toil-cwl-runner.stdout.txt
Saving copy of toil-cwl-runner stderr to: /home/david/git/dockstore/datastore/launcher-c2886001-1125-4529-9173-88506a0c73bf/outputs/toil-cwl-runner.stderr.txt
Provisioning your output files to their final destinations
Registering: #output_file to provision from /home/david/git/dockstorefile:///home/david/git/dockstore/datastore/launcher-c2886001-1125-4529-9173-88506a0c73bf/outputs/md5sum.txt to : /home/david/git/dockstore/out.txt
Provisioning from /home/david/git/dockstorefile:///home/david/git/dockstore/datastore/launcher-c2886001-1125-4529-9173-88506a0c73bf/outputs/md5sum.txt to /home/david/git/dockstore/out.txt
Downloading: file:///home/david/git/dockstorefile:/home/david/git/dockstore/datastore/launcher-c2886001-1125-4529-9173-88506a0c73bf/outputs/md5sum.txt to file:///home/david/git/dockstore/out.txt
100%                                                                

18:08:21.806 [main] ERROR io.dockstore.common.FileProvisioning - plugin threw an exception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not provision output files
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.dockstore.common.FileProvisioning.uploadFiles(FileProvisioning.java:563)
	at io.dockstore.client.cli.nested.CwltoolLauncher.provisionOutputFiles(CwltoolLauncher.java:69)
	at io.github.collaboratory.cwl.CWLClient.provisionOutputFiles(CWLClient.java:262)
	at io.dockstore.client.cli.nested.BaseLanguageClient.launchPipeline(BaseLanguageClient.java:188)
	at io.github.collaboratory.cwl.CWLClient.launch(CWLClient.java:289)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:1159)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:1119)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:271)
	at io.dockstore.client.cli.Client.run(Client.java:709)
	at io.dockstore.client.cli.Client.main(Client.java:611)
Caused by: java.lang.RuntimeException: Could not provision output files
	at io.dockstore.common.FileProvisioning.provisionOutputFile(FileProvisioning.java:512)
	at io.dockstore.common.FileProvisioning.lambda$uploadFiles$11(FileProvisioning.java:557)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.commons.vfs2.FileNotFoundException: Could not read from "file:///home/david/git/dockstorefile:/home/david/git/dockstore/datastore/launcher-c2886001-1125-4529-9173-88506a0c73bf/outputs/md5sum.txt" because it is not a file.
```

To reproduce:

1) change dockstore config and add the line `cwlrunner: toil`
2) `pip3 install toil`

**Comment by denis-yuen** [comment]
David: please don't close, might make more sense to add toil to our testing somewhere so it doesn't break
We need to document to some extent how Toil works since it is an in house project
