### ISSUE TITLE
Login with Google not working on JDK 11

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2479]
## Bug Report

Logging in with Google on the develop branch, which requires Java 11, fails. It is failing with `java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+`.

The exception is caught [here](https://github.com/dockstore/dockstore/blob/47706705a5a90188460df6c84ce29a876c5c7840/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GoogleHelper.java#L159).

When this is fixed, we should change the `LOG.info` to `LOG.error`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-729)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 14 Nordland
┆Issue Number: DOCK-729

**Comment by coverbeck** [comment]
```WARN  [2019-05-11 00:10:31,570] com.google.api.client.googleapis.services.AbstractGoogleClient: Application name is not set. Call Builder#setApplicationName.
java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
	at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:80)
	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:172)
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:652)
	at okhttp3.internal.huc.OkHttpsURLConnection.setSSLSocketFactory(OkHttpsURLConnection.java:63)
	at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:145)
	at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:62)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:872)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at io.dockstore.webservice.helpers.GoogleHelper.tokenInfoFromToken(GoogleHelper.java:155)
	at io.dockstore.webservice.helpers.GoogleHelper.isValidToken(GoogleHelper.java:165)
	at io.dockstore.webservice.helpers.GoogleHelper.userinfoplusFromToken(GoogleHelper.java:124)
	at io.dockstore.webservice.resources.TokenResource.getUserInfo(TokenResource.java:401)
	at io.dockstore.webservice.resources.TokenResource.addGoogleToken(TokenResource.java:335)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

Comment in com/squareup/okhttp3/okhttp/3.9.1/okhttp-3.9.1.jar!/okhttp3/OkHttpClient.class
```
 /**
     * Sets the socket factory used to secure HTTPS connections. If unset, the system default will
     * be used.
     *
     * @deprecated {@code SSLSocketFactory} does not expose its {@link X509TrustManager}, which is
     *     a field that OkHttp needs to build a clean certificate chain. This method instead must
     *     use reflection to extract the trust manager. Applications should prefer to call {@link
     *     #sslSocketFactory(SSLSocketFactory, X509TrustManager)}, which avoids such reflection.
     */
    public Builder sslSocketFactory(SSLSocketFactory sslSocketFactory) {
   ```

But it's Google client code which is calling this method.

**Comment by garyluu** [comment]
Possibly need to replace everything with https://github.com/googleapis/google-auth-library-java .  Even then, it may not work.

**Comment by denis-yuen** [comment]
Seems functional (staging used Java 11, can login using Google on staging)
