### ISSUE TITLE
1.7.0-beta.2

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2727]
### Expected behaviour
https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0?tab=info should run
`/dockstore tool launch --entry quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0 --json Dockstore_cwl.json` with dockstore 1.7.0-beta.2 pointed at staging

### Actual behaviour
```
gluu@ODL-GARYLUU:~/Seqware-BWA-Workflow$ ./dockstore tool launch --entry quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0 --json Dockstore_cwl.json 
dockstore needs to be on PATH for certain commands to work (like --upgrade)
[##################################################] 100%
Created temporary working directory at '/tmp/1565279086032-0'
11:44:46.380 [main] ERROR io.dockstore.client.cli.ArgumentUtility - The tool entry does not exist. Did you mean to launch a local tool or a workflow?
11:44:46.382 [main] ERROR io.dockstore.client.cli.ArgumentUtility - io.swagger.client.ApiException: {"code":500,"message":"There was an error processing your request. It has been logged (ID 5c0879d8bbd2fd97)."}
	at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:718)
	at io.dockstore.client.cli.SwaggerUtility.getArbitraryURL(SwaggerUtility.java:43)
	at io.dockstore.client.cli.nested.ToolClient.downloadTargetEntry(ToolClient.java:663)
	at io.dockstore.client.cli.nested.BaseLanguageClient.initializeWorkingDirectoryWithFiles(BaseLanguageClient.java:223)
	at io.github.collaboratory.cwl.CWLClient.downloadFiles(CWLClient.java:271)
	at io.dockstore.client.cli.nested.BaseLanguageClient.launchPipeline(BaseLanguageClient.java:150)
	at io.github.collaboratory.cwl.CWLClient.launch(CWLClient.java:289)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:1200)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:1160)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:278)
	at io.dockstore.client.cli.Client.run(Client.java:711)
	at io.dockstore.client.cli.Client.main(Client.java:611)
```

Webservice has:

```
ERROR [2019-08-08 15:44:46,377] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 5c0879d8bbd2fd97
! java.lang.NullPointerException: null
! at io.dockstore.webservice.helpers.EntryVersionHelper.writeStreamAsZip(EntryVersionHelper.java:352)
! at io.dockstore.webservice.resources.DockerRepoResource.lambda$getToolZip$15(DockerRepoResource.java:1110)
```
### Steps to reproduce the behaviour 

- git clone ICGC-TCGA-PanCancer/Seqware-BWA-Workflow
- git checkout 2.7.0
- download dockstore 1.7.0-beta.2
- ./dockstore tool launch --entry quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0 --json Dockstore_cwl.json

More notes:
It doesn't work for 1.6.0 pointed at production either

**Comment by denis-yuen** [comment]
Not clear from the ticket, is this happening for other versions of pcawg-bwa-mem-workflow? Does it happen for all workflows?

**Comment by garyluu** [comment]
That should be part of the investigation for this issue (debugging, breakpoint, etc).  Right now, tooltester doesn't run other ones because they've been blacklisted by the /var/spool/cwl issue.  As for the 2nd question, it doesn't happen for all tools/workflows.  Plenty of other tools/workflows run fine.

**Comment by denis-yuen** [comment]
@garyluu please investigate from a user point of view, same with the other ticket
i.e. run different versions of the workflow with the client without debugging, breakpoints, etc. 
Giving me an idea as to the severity of the issue will help me prioritize/assign people, thanks!

**Comment by garyluu** [comment]
I'll assign this issue to myself then.  No user in their right mind will try to run multiple workflow versions that may or may not work to compare with something that doesn't work.

**Comment by garyluu** [comment]
I've already mentioned that the other workflow versions will not run.

**Comment by garyluu** [comment]
Caused by the `/Dockstore_cwl.json` have no content

**Comment by garyluu** [comment]
Doesn't happen with other workflow versions or other workflows btw.  But the other workflow versions fail further down the line for other reasons.
