### ISSUE TITLE
shared workflows 500 with valid google token

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#2794]
### Expected behaviour

No exception if I'm logged in with Google (but haven't registered in FireCloud/Terra)
Results in a 500 pop-up as well

### Actual behaviour

Exception on checking Sam permissions 
```
ERROR [2019-08-23 19:22:29,036] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 4fe7b9535fb042ed
! java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
! at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:77)
! at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:177)
! at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:743)
! at io.dockstore.webservice.helpers.ObsoleteUrlFactory$OkHttpsURLConnection.setSSLSocketFactory(ObsoleteUrlFactory.java:1190)
! at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:162)
! at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:61)
! at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:920)
! at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:322)
! at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:346)
! at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:577)
! at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:372)
! at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:494)
! at io.dockstore.webservice.helpers.GoogleHelper.lambda$getValidAccessToken$2(GoogleHelper.java:112)
! at java.base/java.util.Optional.orElseGet(Optional.java:369)
! at io.dockstore.webservice.helpers.GoogleHelper.getValidAccessToken(GoogleHelper.java:102)
! at io.dockstore.webservice.permissions.sam.SamPermissionsImpl.googleAccessToken(SamPermissionsImpl.java:445)
! at io.dockstore.webservice.permissions.sam.SamPermissionsImpl.getApiClient(SamPermissionsImpl.java:420)
! at io.dockstore.webservice.permissions.sam.SamPermissionsImpl.getResourcesApi(SamPermissionsImpl.java:127)
! at io.dockstore.webservice.permissions.sam.SamPermissionsImpl.workflowsSharedWithUser(SamPermissionsImpl.java:162)
! at io.dockstore.webservice.resources.WorkflowResource.sharedWorkflows(WorkflowResource.java:780)
```

**Comment by coverbeck** [comment]
@denis-yuen Do you recall if you had relinked your Google account after deploying the new build on staging?

**Comment by denis-yuen** [comment]
Yes, I think I've unlinked-relinked
