### ISSUE TITLE
Not seeing My Entries on new staging home page

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3084]
## Bug Report

On staging, the My Entries section of the logged-in home page displays no entries for me. In the browser inspector, I can see error for the Ajax request.

Debugged it locally, and it's because I have versions with a null dbupdatedate. This [line](https://github.com/dockstore/dockstore/blob/05eba2696a8816f33cc3da78ece41644ec20ac2f/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java#L659) is failing, and I see the following stack trace:
```
! java.lang.NullPointerException: null
! at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
! at java.base/java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
! at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
! at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
! at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
! at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
! at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
! at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:594)
! at io.dockstore.webservice.resources.UserResource.lambda$getUserEntries$12(UserResource.java:659)
```

FWIW, the tool that has the null dbupdatedate values in its versions is quay.io/ucsc_cgl/picardtools. 

I know this works for others; I don't know why I in particular am running into this.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1119)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 26 Abalone
┆Issue Number: DOCK-1119

**Comment by coverbeck** [comment]
This works for me on staging (and I was one person seeing the error).

API - 1.8.0-rc.0
UI - 2.5.0-rc.0
