### ISSUE TITLE
Unrecognized field in dropwizard yml: orcidAuthUrl, orcidRedirectPath, orcidScope

### ISSUE THREAD

**Issue by chmreid** [dockstore/dockstore#3433]
**Describe the bug**

Following the instructions on the [OICR wiki](https://wiki.oicr.on.ca/display/DOC/Setting+Up+Dockstore+Locally), I am running the webservice and using a modified version of the dockstore.yml file in this repo: https://github.com/dockstore/dockstore/blob/develop/dockstore-integration-testing/src/test/resources/dockstore.yml

But the dockstore webservice encounters an error with three of the options present in the sample dockstore.yml in the `uiConfig` section:

```
uiConfig:
  orcidAuthUrl: https://sandbox.orcid.org/oauth/authorize
  orcidRedirectPath: /auth/orcid.org
  orcidScope: /authorize
```

When any one of them are included, running the webservice fails with the following error message:

```plain
vagrant@ubuntu-bionic:~/dockstore$ java -jar dockstore-webservice/target/dockstore-webservice-1.8.2.jar server ~/.dockstore/dropwizard.yml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/home/vagrant/dockstore/dockstore-webservice/target/dockstore-webservice-1.8.2.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
io.dropwizard.configuration.ConfigurationParsingException: /home/vagrant/.dockstore/dropwizard.yml has an error:
  * Unrecognized field at: uiConfig.orcidScope
    Did you mean?:
      - googleScope
      - zenodoScope
      - gitHubScope
      - quayIoScope
      - gitlabScope
        [19 more]

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)

	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.dockstore.webservice.DockstoreWebserviceApplication.main(DockstoreWebserviceApplication.java:157)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "orcidScope" (class io.dockstore.webservice.DockstoreWebserviceConfiguration$UIConfig), not marked as ignorable (24 known properties: "dnaNexusImportUrl", "quayIoRedirectPath", "featuredContentUrl", "quayIoAuthUrl", "gitlabAuthUrl", "tagManagerId", "bitBucketAuthUrl", "gitHubScope", "bdCatalystSevenBridgesImportUrl", "bdCatalystTerraImportUrl", "cwlVisualizerUri", "gitHubAppInstallationUrl", "zenodoRedirectPath", "dnaStackImportUrl", "terraImportUrl", "googleScope", "gitlabRedirectPath", "zenodoScope", "gitHubAuthUrl", "zenodoAuthUrl", "quayIoScope", "documentationUrl", "gitlabScope", "gitHubRedirectPath"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.dockstore.webservice.DockstoreWebserviceConfiguration["uiConfig"]->io.dockstore.webservice.DockstoreWebserviceConfiguration$UIConfig["orcidScope"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2277)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more
```

**To Reproduce**

Follow the wiki instructions, finish building dockstore from source, set the appropriate values in the dropwizard file `~/.dockstore/dockstore.yml` (here I am calling it `~/.dockstore/dropwizard.yml`), and attempt to start the webservice with the command:

```
$ java -jar dockstore-webservice/target/dockstore-webservice-1.8.2.jar server ~/.dockstore/dropwizard.yml
```

**Expected behavior**

Sample yaml file at <https://github.com/dockstore/dockstore/blob/develop/dockstore-integration-testing/src/test/resources/dockstore.yml> should contain only valid options.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Browser: N/A
 - Dockstore Version 1.8.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1339)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1339

**Comment by coverbeck** [comment]
Those settings are for 1.9.x, and do work if you are running off develop branch. 

Are you trying an older branch/tag purpose? In any case, could you please update the doc accordingly?

**Comment by chmreid** [comment]
> Those settings are for 1.9.x, and do work if you are running off develop branch.

Ah, I was using the 1.8.2 tag, so that explains it! I will update the docs to make a note of this.

**Comment by denis-yuen** [comment]
Sounds good
