### ISSUE TITLE
GitHub apps lambda errors on an installation events

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3783]
**Describe the bug**
When you install a GitHub app, an error occurs due to an undefined variable.

From an end-user perspective, this does not break anything;  future push events will work correctly.

The only downside from the user-perspective is that the lambda will retry a few times and the user will see duplicate install events in the logs.

From the non-user perspective, it's chewing up a small amount of resources and cluttering our logs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1562)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1562
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by coverbeck** [comment]
This was the error, should have had it in the description: 

```
2020-07-02T17:46:56.685Z	bffd6fea-9101-516d-b915-38928ec1eaf3	ERROR	Uncaught Exception	
{
    "errorType": "ReferenceError",
    "errorMessage": "repository is not defined",
    "stack": [
        "ReferenceError: repository is not defined",
        "    at postEndpoint (/var/task/index.js:142:97)",
        "    at IncomingMessage.<anonymous> (/var/task/index.js:52:16)",
        "    at IncomingMessage.emit (events.js:203:15)",
        "    at IncomingMessage.EventEmitter.emit (domain.js:448:20)",
        "    at endReadableNT (_stream_readable.js:1145:12)",
        "    at process._tickCallback (internal/process/next_tick.js:63:19)"
    ]
}
```

**Comment by coverbeck** [comment]
Can confirm that there are no more "not defined" messages in our logs for the last several release.
