### ISSUE TITLE
Show relevant parameters if an invalid parameter is passed

### ISSUE THREAD

**Issue by amarjandu** [dockstore/dockstore#4910]
The dockstore-cli displays an error when an invalid parameter is passed in, but does not provide any useful information about what is valid.

```
(.venv) CBSEspecter:dockstore-cli amar$ dockstore workflow launch --workflow
14:07:51.647 [main] ERROR io.dockstore.client.cli.ArgumentUtility - com.beust.jcommander.ParameterException: Was passed main parameter '--workflow' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:796)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:455)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:306)
	at io.dockstore.client.cli.Client.run(Client.java:729)
	at io.dockstore.client.cli.Client.main(Client.java:628)
```

I would like the CLI to highlight the invalid parameter and display the relevant arguments for `dockstore workflow launch`.

```
(.venv) CBSEspecter:dockstore-cli amar$ dockstore workflow launch --workflow
Invlaid parameter '--workflow' 
Usage: dockstore workflow launch --help
       dockstore workflow launch [parameters] [command]

Description:
  Launch an entry locally or remotely.

Required parameters:
  --entry <entry>                     Complete workflow path in Dockstore (ex. NCI-GDC/gdc-dnaseq-cwl/GDC_DNASeq:master)
   OR
  --local-entry <local-entry>         Allows you to specify a full path to a local descriptor instead of an entry path


  --json <json file>                  Parameters to the entry in Dockstore, one map for one run, an array of maps for multiple runs
   OR
  --yaml <yaml file>                  Parameters to the entry in Dockstore, one map for one run, an array of maps for multiple runs (only for CWL)
   OR
  --tsv <tsv file>                    One row corresponds to parameters for one run in the dockstore (only for CWL)

Optional parameters:
  --wdl-output-target                 Allows you to specify a remote path to provision output files to ex: s3://oicr.temp/testing-launcher/
  --uuid                              Allows you to specify a uuid for 3rd party notifications
  --ignore-checksums                  Allows you to ignore validating checksums of each downloaded descriptor
---------------------------------------------
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2172)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2172
┆Sprint: 105 - Colorado
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Note "Invlaid" is also odd, copy-paste issue or legit issue withj jcommander to look at as well
