### ISSUE TITLE
CLI YAML validator shouldn't print a stack trace by default

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5186]
**Is your feature request related to a problem? Please describe.**
If there's an error in your .dockstore.yml, the CLI validator will catch it, and display a helpful error message, but the bulk of the output is a stack trace, which makes it hard to find.

**Describe the solution you'd like**
The CLI should only display end-user friendly messages by default (at least for `yaml validate`, perhaps in general).

The stack traces are useful, especially for engineers working on the CLI, and should still be optionally surfaced. Note that there already is a `--debug` command line switch which we could probably use.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
All I had was a case typo, `primarydescriptorPath` instead of `primaryDescriptorPath` -- imagine being a new user and trying to parse the actual problem (all I would care about are the last two lines in this case):
```
dockstore yaml validate --path .
./.dockstore.yml is a valid yaml file
16:12:54.172 [main] ERROR io.dockstore.common.yaml.DockstoreYamlHelper - Error reading .dockstore.yml: Cannot create property=primarydescriptorPath for JavaBean=io.dockstore.common.yaml.YamlWorkflow@6ecab872
 in 'string', line 5, column 7:
       -  name: multi-descriptor-no-input
          ^
Unable to find property 'primarydescriptorPath' on class: io.dockstore.common.yaml.YamlWorkflow
 in 'string', line 7, column 30:
          primarydescriptorPath: workflows/wdl/w2/multiDescriptor ...
                                 ^

org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=workflows for JavaBean=io.dockstore.common.yaml.DockstoreYaml12@48eb9836
 in 'string', line 2, column 1:
    version: 1.2
    ^
Cannot create property=primarydescriptorPath for JavaBean=io.dockstore.common.yaml.YamlWorkflow@6ecab872
 in 'string', line 5, column 7:
       -  name: multi-descriptor-no-input
          ^
Unable to find property 'primarydescriptorPath' on class: io.dockstore.common.yaml.YamlWorkflow
 in 'string', line 7, column 30:
          primarydescriptorPath: workflows/wdl/w2/multiDescriptor ...
                                 ^

 in 'string', line 5, column 4:
       -  name: multi-descriptor-no-input
       ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:291)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:172)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:332)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
	at io.dockstore.common.yaml.DockstoreYamlHelper.readContent(DockstoreYamlHelper.java:213)
	at io.dockstore.common.yaml.DockstoreYamlHelper.checkForUnknownProperty(DockstoreYamlHelper.java:256)
	at io.dockstore.common.yaml.DockstoreYamlHelper$Version$3.validateDockstoreYamlProperties(DockstoreYamlHelper.java:84)
	at io.dockstore.common.yaml.DockstoreYamlHelper.validateDockstoreYamlProperties(DockstoreYamlHelper.java:242)
	at io.dockstore.client.cli.YamlVerifyUtility.dockstoreValidate(YamlVerifyUtility.java:162)
	at io.dockstore.client.cli.YamlClient.handleCommand(YamlClient.java:73)
	at io.dockstore.client.cli.Client.run(Client.java:729)
	at io.dockstore.client.cli.Client.main(Client.java:633)
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=primarydescriptorPath for JavaBean=io.dockstore.common.yaml.YamlWorkflow@6ecab872
 in 'string', line 5, column 7:
       -  name: multi-descriptor-no-input
          ^
Unable to find property 'primarydescriptorPath' on class: io.dockstore.common.yaml.YamlWorkflow
 in 'string', line 7, column 30:
          primarydescriptorPath: workflows/wdl/w2/multiDescriptor ...
                                 ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:291)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:172)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:391)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:375)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:543)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:306)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	... 16 common frames omitted
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'primarydescriptorPath' on class: io.dockstore.common.yaml.YamlWorkflow
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:158)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:148)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:310)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:231)
	... 26 common frames omitted
Your .dockstore.yml is invalid:
./.dockstore.yml has the following errors:
Unknown property: 'primarydescriptorPath'. Did you mean: 'primaryDescriptorPath'?
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2268)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2268
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by coverbeck** [comment]
Just noticed the stack traces may only occur with that particular validation error. A couple of other validation errors don't trigger it:

Missing descriptor:
```
dockstore yaml validate --path .
./.dockstore.yml is a valid yaml file
Your file structure has the following errors:
./workflow/wdl/w2/multiDescriptorNoInput.wdl does not exist
```

Invalid yaml syntax:

```
dockstore yaml validate --path .
Your .dockstore.yml is invalid:
./.dockstore.yml is not a valid yaml file:
mapping values are not allowed here
 in 'string', line 3, column 10:
    workflows:
             ^
```

**Comment by coverbeck** [comment]
Verified this works as expected in 1.14.0-SNAPSHOT
