### ISSUE TITLE
CLIhere: WES always assumes that WDL workflows are version "1.0"

### ISSUE THREAD

**Issue by fhembroff** [dockstore/dockstore#5393]
**Describe the bug**
Currently, we are unable to run WDL workflows that are **not** version "1.0" through WES on the CLI.

This is because we specify what version of WDL we are using for WES [here](https://github.com/dockstore/dockstore-cli/blob/bc0b70ff94158fac9656f978482f9a47ebf96dd4/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java#L121), however, we have set the variable to be always equal to "1.0" [here](https://github.com/dockstore/dockstore-cli/blob/bc0b70ff94158fac9656f978482f9a47ebf96dd4/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java#L110), [here](https://github.com/dockstore/dockstore-cli/blob/bc0b70ff94158fac9656f978482f9a47ebf96dd4/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java#L327) and  [here](https://github.com/dockstore/dockstore-cli/blob/bc0b70ff94158fac9656f978482f9a47ebf96dd4/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java#L40).

This means that any WDL workflow that is not version "1.0" will not run through WES. If a WDL workflow is the wrong version, we see an error that looks like this (found by going through the agc logs),

```
escriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Unrecognized token on line 1, column 1:

task md5 {
^
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:257)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:227)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:222)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at akka.actor.FSM.processEvent(FSM.scala:707)
        at akka.actor.FSM.processEvent$(FSM.scala:704)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:169)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:847)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:829)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:169)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:701)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:695)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:169)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
        at akka.actor.ActorCell.invoke(ActorCell.scala:583)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


Wed, 01 Mar 2023 18:31:44 -0500 2023-03-01 23:31:44,414 cromwell-system-akka.dispatchers.engine-dispatcher-24 INFO  - WorkflowManagerActor: Workflow actor for 43202783-9e73-496d-aa7a-63446f56bfd5 completed with status 'Failed'. The workflow will be removed from the workflow store.

```

**To Reproduce**
Attempt to launch [this workflow](https://qa.dockstore.org/workflows/github.com/briandoconnor/dockstore-workflow-md5sum/dockstore-wdl-workflow-md5sum:1.4.0?tab=launch) on AGC using the provided commands.

**Expected behavior**
The CLI should be able to run all WDL versions (particularly version `draft-2`, as it is used a lot on dockstore.org).

**Additional context**
**CLI VERSION:**  1.13.1

I also found that if modify this [line](https://github.com/dockstore/dockstore-cli/blob/bc0b70ff94158fac9656f978482f9a47ebf96dd4/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WesLauncher.java#L121) to `draft-2` the workflow in the "To reproduce" section will work.

**Comment by fhembroff** [comment]
I think this should be fairly easy to correct.

I think all you would have to do is check the WDL file for something that looks like `version: X` and if it doesn't exist, the WDL is version `draft-2`, and if it does you just return whatever `X` is.

**Comment by coverbeck** [comment]
There's [code in the web service](https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/WDLHandler.java#L593) that gets the version of a WDL file. It would be good to reuse that, although that code is currently not accessible by the CLI.
