### ISSUE TITLE
Openapi definition for relative path endpoint seems inconsistent

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5396]
**Describe the bug**
Looks like an inconsistency between the TRS definition ( https://github.com/ga4gh/tool-registry-service-schemas/blob/v2.0.1/openapi/openapi.yaml#L266-L273 ) and our webservice ( https://github.com/dockstore/dockstore/blob/1.14.0-alpha.7/dockstore-webservice/src/main/resources/openapi3/openapi.yaml#L2956-L2963 ) seems to be causing an issue with the generated openapi (possibly swagger as well) Java client

**To Reproduce**
```
final FileWrapper remoteDescriptor = ga4Ghv20Api.toolsIdVersionsVersionIdTypeDescriptorRelativePathGet("PLAIN_WDL", "#workflow/github.com/dockstore-testing/wes-testing/agc-fastq-read-counts", "main", "/agc-examples/fastq/input.json");
```
causes message like 
```
Exception in thread "main" org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class io.dockstore.openapi.client.model.FileWrapper, genericType=class io.dockstore.openapi.client.model.FileWrapper.
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:208)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:888)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:848)
        at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340)
        at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:104)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
        at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244)
        at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:101)
        at io.dockstore.openapi.client.ApiClient.deserialize(ApiClient.java:589)
        at io.dockstore.openapi.client.ApiClient.invokeAPI(ApiClient.java:728)
        at io.dockstore.openapi.client.api.Ga4Ghv20Api.toolsIdVersionsVersionIdTypeDescriptorRelativePathGet(Ga4Ghv20Api.java:441)
        at io.dockstore.tooltester.client.cli.Client.runToolTesterOnWorkflows(Client.java:317)
        at io.dockstore.tooltester.client.cli.Client.main(Client.java:171)
```

**Expected behavior**
Should be able to get plain text representation

Current workaround is the `WDL` or JSON representation seems to work

**Comment by denis-yuen** [comment]
May be https://github.com/swagger-api/swagger-codegen/issues/11124

**Comment by denis-yuen** [comment]
FYI @fhembroff there may not be an obvious solution for this.

**Comment by denis-yuen** [comment]
Bit of a summary:
1) When the TRS openapi is put through `swagger-codegen-maven-plugin` to generate swever stubs, it seems to only render one api response 
```
    @Produces({ "application/json", "text/plain" })
      @Operation(summary = "Get additional tool descriptor files relative to the main file", description = "Descriptors can often include imports that refer to additional descriptors. This returns additional descriptors for the specified tool in the same or other directories that can be reached as a relative path. This endpoint can be useful for workflow engine implementations like cwltool to programmatically download all the descriptors for a tool and run it. This can optionally include other files described with FileWrappers such as test parameters and containerfiles.", security = {
      @SecurityRequirement(name = "BEARER")      }, tags={"GA4GHV20"})
      @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The tool descriptor.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = FileWrapper.class))),
        
        @ApiResponse(responseCode = "404", description = "The tool can not be output in the specified type.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
```
i.e. it says both text and json are possible, but only a FileWrapper type is noted as an ApiResponse

2) As a result, `swagger-maven-plugin` also generates an inconsistent openapi.yaml as noted above where the 'text/plain` response is given a FileWrapper schema which is weird

3) This results in a broken openapi client for this specific endpoint. Ugh

Preliminary exam of dependency updates doesn't reveal an obvious upstream fix
