### ISSUE TITLE
Error running updateOpenData

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5496]
**Describe the bug**
There was an error running the `/entries/updateOpenData` endpoint in staging

**To Reproduce**
1. Invoke `/entries/updateOpenData` endpoint as admin
2. See error

```
"POST /entries/updateOpenData?allVersions=true HTTP/1.0" 500 110 "https://staging.dockstore.org/api/static/swagger-ui/index.html" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" 409596
	2023-05-04T15:53:28.185-04:00	ERROR [2023-05-04 19:53:28,183] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 33922ec20a3d2c51
	2023-05-04T15:53:28.185-04:00	! java.lang.StackOverflowError: null
	2023-05-04T15:53:28.185-04:00	! at scala.collection.IndexedSeqOps.lengthCompare(IndexedSeq.scala:102)
	2023-05-04T15:53:28.185-04:00	! at scala.collection.IndexedSeqOps.lengthCompare$(IndexedSeq.scala:102)
	2023-05-04T15:53:28.185-04:00	! at scala.collection.immutable.Vector.lengthCompare(Vector.scala:113)
	2023-05-04T15:53:28.185-04:00	! at scala.collection.SeqOps.isEmpty(Seq.scala:842)
	2023-05-04T15:53:28.185-04:00	! at scala.collection.SeqOps.isEmpty$(Seq.scala:842)
	2023-05-04T15:53:28.185-04:00	! at scala.collection.AbstractSeq.isEmpty(Seq.scala:1188)
```

**Expected behavior**
It should run without an error

**Additional context**
[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0-beta.0) - 2.11.0-beta.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2394)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2394
┆Sprint: 112 - Jialing
┆Issue Type: Story

**Comment by coverbeck** [comment]
See #5291; similar problem.
