### ISSUE TITLE
Calling GET endpoint for workflows and tools with unusual filter fails with 500 error

### ISSUE THREAD

**Issue by hyunnaye** [dockstore/dockstore#5504]
**Describe the bug**
During community lead, found 500 errors for attempts of getting workflows and tools without providing the actual workflow/tool.
Interesting that it used a python library.

Called endpoint for workflow:
```
127.0.0.1 - - [10/May/2023:15:42:34 +0000] "GET /workflows/published?offset=42&limit=42&filter=string%20value&sortCol=string%20value&sortOrder=string%20value&services=True&subclass=BIOWORKFLOW HTTP/1.0" 500 110 "-" "python-urllib3/1.26.15" 14
```
Stack trace:
```
2023-05-10T15:42:34.625Z | ERROR [2023-05-10 15:42:34,624] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: eedd6f1addd982b4
-- | --
  | 2023-05-10T15:42:34.625Z | ! java.lang.IllegalArgumentException: Unable to locate Attribute with the the given name [string value] on this ManagedType [io.dockstore.webservice.core.Entry]
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.checkNotNull(AbstractManagedType.java:148)
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:119)
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:117)
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:117)
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:44)
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.query.criteria.internal.path.AbstractFromImpl.locateAttributeInternal(AbstractFromImpl.java:111)
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.query.criteria.internal.path.AbstractPathImpl.locateAttribute(AbstractPathImpl.java:204)
  | 2023-05-10T15:42:34.625Z | ! at org.hibernate.query.criteria.internal.path.AbstractPathImpl.get(AbstractPathImpl.java:177)
  | 2023-05-10T15:42:34.625Z | ! at io.dockstore.webservice.jdbi.EntryDAO.processQuery(EntryDAO.java:354)
  | 2023-05-10T15:42:34.625Z | ! at io.dockstore.webservice.jdbi.EntryDAO.findAllPublished(EntryDAO.java:268)
  | 2023-05-10T15:42:34.625Z | ! at io.dockstore.webservice.resources.WorkflowResource.allPublishedWorkflows(WorkflowResource.java:811)

```

Called endpoint for tool:
```
127.0.0.1 - - [10/May/2023:15:42:34 +0000] "GET /containers/published?offset=42&limit=42&filter=string%20value&sortCol=string%20value&sortOrder=string%20value HTTP/1.0" 500 110 "-" "python-urllib3/1.26.15" 19
```
Stack trace:
```
2023-05-10T15:42:34.928Z | ERROR [2023-05-10 15:42:34,928] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 4efcd16f2b44cf57
-- | --
  | 2023-05-10T15:42:34.928Z | ! java.lang.IllegalArgumentException: Unable to locate Attribute with the the given name [string value] on this ManagedType [io.dockstore.webservice.core.Entry]
  | 2023-05-10T15:42:34.928Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.checkNotNull(AbstractManagedType.java:148)
  | 2023-05-10T15:42:34.928Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:119)
  | 2023-05-10T15:42:34.928Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:117)
  | 2023-05-10T15:42:34.928Z | ! at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:44)
  | 2023-05-10T15:42:34.928Z | ! at org.hibernate.query.criteria.internal.path.AbstractFromImpl.locateAttributeInternal(AbstractFromImpl.java:111)
  | 2023-05-10T15:42:34.928Z | ! at org.hibernate.query.criteria.internal.path.AbstractPathImpl.locateAttribute(AbstractPathImpl.java:204)
  | 2023-05-10T15:42:34.928Z | ! at org.hibernate.query.criteria.internal.path.AbstractPathImpl.get(AbstractPathImpl.java:177)
  | 2023-05-10T15:42:34.928Z | ! at io.dockstore.webservice.jdbi.EntryDAO.processQuery(EntryDAO.java:354)
  | 2023-05-10T15:42:34.928Z | ! at io.dockstore.webservice.jdbi.EntryDAO.findAllPublished(EntryDAO.java:268)
  | 2023-05-10T15:42:34.928Z | ! at io.dockstore.webservice.jdbi.EntryDAO.findAllPublished(EntryDAO.java:251)
  | 2023-05-10T15:42:34.928Z | ! at io.dockstore.webservice.resources.DockerRepoResource.allPublishedContainers(DockerRepoResource.java:800)
  | 2023-05-10T15:42:34.928Z | ! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```
**Expected behavior**
Should be a 4xx.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2397)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11023">image-20230620-210055.png</a>
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2397
┆Sprint: 114 - Mekong
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Looking at the stack traces, it looks like some issue creating the hibernate/jpa criteria builders to construct a query to retrieve workflows/tools. 
I'm suspicious of the `filter=string%20value` argument

**Comment by denis-yuen** [comment]
For example, a working request is https://dockstore.org/api/workflows/published?offset=0&limit=10&filter=covid&sortCol=stars&sortOrder=desc&services=false&subclass=BIOWORKFLOW
