### ISSUE TITLE
Investigate Hibernate assertion when getting a checker workflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5654]
**Describe the bug**
If Java assertions are enabled, an assertion happens in Hibernate's PersistentMap class . Ideally, since they have the assert for a reason, that should not be happening, and we should figure out if we have some sort of Hibernate mapping misconfiguration.

Spun off from dockstore/dockstore-cli#256

If this is fixed in the web service, also remove the disable assertions from this [PR](https://github.com/dockstore/dockstore-cli/pull/256/files#diff-a745e2892b7c92cb498408866d62774692b44eb5c5844bd884baaecd112d5dedR271) in the CLI.

**To Reproduce**
We can't run the web service with assertions enabled for non-Hibernate reasons (could be another bug), so:
1. Run the web service locally with the debugger, with a snapshot of prod data.
2. Set a conditional breakpoint in org.hibernate.collection.spi.PersistentMap#injectLoadedState, on the `assert isInitializing()`. See screenshot.
3. Invoke the workflow by path endpoint:
```
curl -X 'GET' \
  'http://localhost:8080/workflows/path/workflow/github.com%2FDataBiosphere%2Ftopmed-workflows%2Fchecker_UM_variant_caller_wdl?subclass=BIOWORKFLOW' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <redacted>'
```
4. Breakpoint will get hit, which means the assertion would fail if assertions were turned on.

Note: credentials are required to reproduce the bug. I think it might be related to loading UserProfiles twice, once for user authentication, and once as a user of the workflow, but that's a hypothesis. It may happen with other endpoints, but that's the only one I've seen so far.

**Expected behavior**
The breakpoint should not be hit.

**Screenshot**
![Screen Shot 2023-09-01 at 4 31 44 PM](https://github.com/dockstore/dockstore/assets/1049340/e5882b4e-09c2-40b7-acc0-6734b65c11fd)

**Additional context**
[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/7da93c1) - 7da93c1

[UI](https://github.com/dockstore/dockstore-ui2/commits/6b02daed) - 2.11.1-61-g6b02daed

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/6b95051) - 1.14.1-39-g6b95051

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a

**Comment by denis-yuen** [comment]
Note to self: 
Startup issue is an easy classpath fix, will need testing. 
The check is interesting, overriding with Hibernate 6.2.2 or 6.3.0 fails entirely for unrelated reasons.

**Comment by denis-yuen** [comment]
Alternative lead: If I switch the checker workflow relationship to eager, I get a totally different error 
`org.hibernate.AssertionFailure: force initializing collection loading
	at org.hibernate.collection.spi.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:811)
	at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:1003)
	at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:989)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:225)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at 
`
https://discourse.hibernate.org/t/force-initializing-collection-loading/7172

**Comment by denis-yuen** [comment]
Could be https://stackoverflow.com/questions/76359070/how-can-i-fix-assertionfailure-when-using-findbycustomerandproduct-in-spring-boo 
May need to wait for new Dropwizard release, was unable to override hibernate version alone

**Comment by denis-yuen** [comment]
> Alternative lead: If I switch the checker workflow relationship to eager, I get a totally different error

Wild. So after discussion with @coverbeck , discovered the other side of the relationship. 
If I flip both to eager, it works, albeit really slowly ...
