### ISSUE TITLE
gs plugin for CLI appears to be broken

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5680]
**Describe the bug**
The [gs plugin for the CLI](https://github.com/dockstore/gs-plugin) doesn't appear to be working anymore, or, alternatively, I'm silly and misunderstand our documentation on how to use it.

**To Reproduce**

1. Install the dockstore CLI version 1.14.0
1. `dockstore plugin download`
1. Verify the gs plugin is installed via `dockstore plugin list`
1. `gcloud auth login` to make sure I'm authenticated
1. Verify the files are in a public Google bucket that is not requester-pays
1. Verify I can download the files referenced in my JSON using gsutil: `gsutil cp gs://ucsc-pathogen-genomics-public/tb/fq/SAMEA3512769_ERR987753_1.fastq .`
1. `dockstore workflow launch --local-entry myco_simple.wdl --json inputs/myco_simple.json`
1. Cromwell throws an error.

**Expected behavior**
Previously the plugin helped Cromwell worked seamlessly with gs URIs, provided they were in a public non-requester-pays bucket.

**Desktop:**

* OS: Mac OS Ventura 13.4
* Hardware: 2019 Intel Mac
* Version: Dockstore CLI version 1.14.0, gs plugin version 0.0.2

**Terminal output**

<details>
<summary>Verbose log here</summary>
<br>

Current version : 1.14.0
You have the most recent stable release.
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
Created temporary working directory at '/var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/1695843692910-0'
Using local file 'myco_simple.wdl' as primary descriptor
Creating directories for run of Dockstore launcher in current working directory: /Users/aofarrel/github/myco
Provisioning your input files to your local machine
Calling out to Cromwell to run your workflow
Executing: java -jar /Users/aofarrel/.dockstore/libraries/cromwell-84.jar run --inputs /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo3720222495255578989json /Users/aofarrel/github/myco/myco_simple.wdl
[2023-09-27 12:41:36,07] [info] Running with database db.url = jdbc:hsqldb:mem:c770c17c-3289-4996-b1f8-922ec9c282c2;shutdown=false;hsqldb.tx=mvcc
[2023-09-27 12:41:38,06] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2023-09-27 12:41:38,07] [info] [RenameWorkflowOptionsInMetadata] 100%
[2023-09-27 12:41:38,24] [info] Running with database db.url = jdbc:hsqldb:mem:d1d70b5b-ead5-4848-82b1-f14f17932a66;shutdown=false;hsqldb.tx=mvcc
[2023-09-27 12:41:38,53] [info] Slf4jLogger started
[2023-09-27 12:41:38,66] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-b69d90e",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2023-09-27 12:41:38,69] [info] Metadata summary refreshing every 1 second.
[2023-09-27 12:41:38,69] [info] No metadata archiver defined in config
[2023-09-27 12:41:38,69] [info] No metadata deleter defined in config
[2023-09-27 12:41:38,70] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2023-09-27 12:41:38,70] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2023-09-27 12:41:38,71] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2023-09-27 12:41:38,76] [info] JobRestartCheckTokenDispenser - Distribution rate: 50 per 1 seconds.
[2023-09-27 12:41:38,78] [info] JobExecutionTokenDispenser - Distribution rate: 20 per 10 seconds.
[2023-09-27 12:41:38,81] [info] SingleWorkflowRunnerActor: Version 84
[2023-09-27 12:41:38,83] [info] SingleWorkflowRunnerActor: Submitting workflow
[2023-09-27 12:41:38,86] [info] Unspecified type (Unspecified version) workflow a27cd496-f1fd-4b7d-aaa9-03e142145664 submitted
[2023-09-27 12:41:38,87] [info] SingleWorkflowRunnerActor: Workflow submitted a27cd496-f1fd-4b7d-aaa9-03e142145664
[2023-09-27 12:41:38,88] [info] 1 new workflows fetched by cromid-b69d90e: a27cd496-f1fd-4b7d-aaa9-03e142145664
[2023-09-27 12:41:38,88] [info] WorkflowManagerActor: Starting workflow a27cd496-f1fd-4b7d-aaa9-03e142145664
[2023-09-27 12:41:38,89] [info] WorkflowManagerActor: Successfully started WorkflowActor-a27cd496-f1fd-4b7d-aaa9-03e142145664
[2023-09-27 12:41:38,89] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2023-09-27 12:41:38,90] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2023-09-27 12:41:38,95] [info] MaterializeWorkflowDescriptorActor [a27cd496]: Parsing workflow as WDL 1.0
[2023-09-27 12:41:40,44] [info] MaterializeWorkflowDescriptorActor [a27cd496]: Call-to-Backend assignments: Tree_Nine.convert_to_nextstrain_subtrees -> Local, Tree_Nine.convert_to_newick -> Local, Tree_Nine.summarize_output_tree -> Local, Tree_Nine.summarize_input_tree -> Local, Tree_Nine.usher_sampled_diff -> Local, Tree_Nine.annotate_input_tree -> Local, Tree_Nine.annotate_output_tree -> Local, FastqcWF.fastqc -> Local, myco.variant_call_each_sample -> Local, Tree_Nine.convert_to_nextstrain_single -> Local, Tree_Nine.reroot -> Local, myco.make_mask_and_diff -> Local, Tree_Nine.cat_diff_files -> Local, Tree_Nine.convert_to_taxonium -> Local, Tree_Nine.summarize_output_tree_before_reroot -> Local
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, bootDiskSizeGb, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, bootDiskSizeGb, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, bootDiskSizeGb, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:40,55] [warn] Local [a27cd496]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2023-09-27 12:41:43,77] [info] Not triggering log of restart checking token queue status. Effective log interval = None
[2023-09-27 12:41:43,79] [info] Not triggering log of execution token queue status. Effective log interval = None
[2023-09-27 12:41:44,69] [info] WorkflowExecutionActor-a27cd496-f1fd-4b7d-aaa9-03e142145664 [a27cd496]: Starting myco.variant_call_each_sample
[2023-09-27 12:41:48,80] [info] Assigned new job execution tokens to the following groups: a27cd496: 1
[2023-09-27 12:41:49,84] [info] WorkflowManagerActor: Workflow a27cd496-f1fd-4b7d-aaa9-03e142145664 failed (during ExecutingWorkflowState): cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1$$anon$1: Call input and runtime attributes evaluation failed for variant_call_each_sample:
Failed to evaluate input 'finalDiskSize' (reason 1 of 1): ValueEvaluator[IdentifierLookup]: No suitable input for 'size_in' amongst {crash_on_timeout, force, ssd, preempt, keep_bam, debug, tarball_bams_and_bais, cpu, timeout, mem_height, arg_debug, addldisk, retries, arg_keep_bam, crash_on_error, basename_reads, sample_name, arg_mem_height, diskType, arg_force, reads_files, memory}
Failed to evaluate input 'size_in' (reason 1 of 2): java.lang.IllegalArgumentException: Could not build the path "gs://ucsc-pathogen-genomics-public/tb/fq/SAMEA3512769_ERR987753_1.fastq". It may refer to a filesystem not supported by this instance of Cromwell. Supported filesystems are: HTTP, MacOSXFileSystem. Failures: 
HTTP: gs://ucsc-pathogen-genomics-public/tb/fq/SAMEA3512769_ERR987753_1.fastq does not have an http or https scheme (IllegalArgumentException)
MacOSXFileSystem: Cannot build a local path from gs://ucsc-pathogen-genomics-public/tb/fq/SAMEA3512769_ERR987753_1.fastq (RuntimeException)
 Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
Failed to evaluate input 'size_in' (reason 2 of 2): java.lang.IllegalArgumentException: Could not build the path "gs://ucsc-pathogen-genomics-public/tb/fq/SAMEA3512769_ERR987753_2.fastq". It may refer to a filesystem not supported by this instance of Cromwell. Supported filesystems are: HTTP, MacOSXFileSystem. Failures: 
HTTP: gs://ucsc-pathogen-genomics-public/tb/fq/SAMEA3512769_ERR987753_2.fastq does not have an http or https scheme (IllegalArgumentException)
MacOSXFileSystem: Cannot build a local path from gs://ucsc-pathogen-genomics-public/tb/fq/SAMEA3512769_ERR987753_2.fastq (RuntimeException)
 Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems

[2023-09-27 12:41:53,74] [info] WorkflowManagerActor: Workflow actor for a27cd496-f1fd-4b7d-aaa9-03e142145664 completed with status 'Failed'. The workflow will be removed from the workflow store.
[2023-09-27 12:41:54,49] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2023-09-27 12:41:58,72] [info] Workflow polling stopped
[2023-09-27 12:41:58,73] [info] 0 workflows released by cromid-b69d90e
[2023-09-27 12:41:58,73] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2023-09-27 12:41:58,74] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2023-09-27 12:41:58,74] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2023-09-27 12:41:58,74] [info] Aborting all running workflows.
[2023-09-27 12:41:58,74] [info] JobExecutionTokenDispenser stopped
[2023-09-27 12:41:58,74] [info] WorkflowStoreActor stopped
[2023-09-27 12:41:58,74] [info] WorkflowLogCopyRouter stopped
[2023-09-27 12:41:58,74] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2023-09-27 12:41:58,74] [info] WorkflowManagerActor: All workflows finished
[2023-09-27 12:41:58,74] [info] WorkflowManagerActor stopped
[2023-09-27 12:41:58,87] [info] Connection pools shut down
[2023-09-27 12:41:58,87] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2023-09-27 12:41:58,87] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2023-09-27 12:41:58,87] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2023-09-27 12:41:58,87] [info] SubWorkflowStoreActor stopped
[2023-09-27 12:41:58,87] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2023-09-27 12:41:58,87] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2023-09-27 12:41:58,87] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2023-09-27 12:41:58,87] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2023-09-27 12:41:58,87] [info] JobStoreActor stopped
[2023-09-27 12:41:58,87] [info] CallCacheWriteActor stopped
[2023-09-27 12:41:58,87] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2023-09-27 12:41:58,87] [info] KvWriteActor Shutting down: 0 queued messages to process
[2023-09-27 12:41:58,87] [info] IoProxy stopped
[2023-09-27 12:41:58,87] [info] DockerHashActor stopped
[2023-09-27 12:41:58,87] [info] ServiceRegistryActor stopped
[2023-09-27 12:41:58,88] [info] Database closed
[2023-09-27 12:41:58,88] [info] Stream materializer shut down
[2023-09-27 12:41:58,88] [info] WDL HTTP import resolver closed
[2023-09-27 12:41:58,89] [info] Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
[2023-09-27 12:41:58,89] [info] Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
[2023-09-27 12:41:58,89] [info] Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
Workflow a27cd496-f1fd-4b7d-aaa9-03e142145664 transitioned to state Failed
12:41:58.968 [main] ERROR io.dockstore.common.Utilities - problems running command: java -jar /Users/aofarrel/.dockstore/libraries/cromwell-84.jar run --inputs /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo3720222495255578989json /Users/aofarrel/github/myco/myco_simple.wdl
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.base/java.lang.Thread.run(Thread.java:833)
12:41:58.972 [main] ERROR io.dockstore.client.cli.nested.BaseLanguageClient - Problem running launcherCromwell: 
java.lang.IllegalStateException: problems running command: {}java -jar /Users/aofarrel/.dockstore/libraries/cromwell-84.jar run --inputs /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo3720222495255578989json /Users/aofarrel/github/myco/myco_simple.wdl
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:190)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:106)
	at io.dockstore.client.cli.nested.BaseLauncher.executeEntry(BaseLauncher.java:124)
	at io.dockstore.client.cli.nested.BaseLanguageClient.commonExecutionCode(BaseLanguageClient.java:438)
	at io.github.collaboratory.wdl.WDLClient.executeEntry(WDLClient.java:154)
	at io.dockstore.client.cli.nested.BaseLanguageClient.launchPipeline(BaseLanguageClient.java:211)
	at io.github.collaboratory.wdl.WDLClient.launch(WDLClient.java:82)
	at io.dockstore.client.cli.nested.WorkflowClient.checkEntryFile(WorkflowClient.java:579)
	at io.dockstore.client.cli.nested.WorkflowClient.launchWithArgs(WorkflowClient.java:525)
	at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:475)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:352)
	at io.dockstore.client.cli.Client.run(Client.java:751)
	at io.dockstore.client.cli.Client.main(Client.java:646)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: {}java -jar /Users/aofarrel/.dockstore/libraries/cromwell-84.jar run --inputs /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo3720222495255578989json /Users/aofarrel/github/myco/myco_simple.wdl (Exit value: 1)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:186)
	... 12 common frames omitted
Cromwell exit code: 1
ERROR: problems running command: [java, -jar, /Users/aofarrel/.dockstore/libraries/cromwell-84.jar, run, --inputs, /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo3720222495255578989json, /Users/aofarrel/github/myco/myco_simple.wdl] (Exit value: 1)
ERROR: problems running command: [java, -jar, /Users/aofarrel/.dockstore/libraries/cromwell-84.jar, run, --inputs, /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo3720222495255578989json, /Users/aofarrel/github/myco/myco_simple.wdl] (Exit value: 1)

</details>

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2467)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2467
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Could be a problem later in the process. Would have thought input files were downloaded roughly here in the logs 
```
Using local file 'myco_simple.wdl' as primary descriptor
Creating directories for run of Dockstore launcher in current working directory: /Users/aofarrel/github/myco
Provisioning your input files to your local machine
Calling out to Cromwell to run your workflow
Executing: java -jar /Users/aofarrel/.dockstore/libraries/cromwell-84.jar run --inputs /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo3720222495255578989json /Users/aofarrel/github/myco/myco_simple.wdl
[2023-09-27 12:41:36,07] [info] Running with database db.url = jdbc:hsqldb:mem:c770c17c-3289-4996-b1f8-922ec9c282c2;shutdown=false;hsqldb.tx=mvcc
```

**Comment by aofarrel** [comment]
> Could be a problem later in the process.

That could well be it, since I'm having issues with the downloaded fastqs too now. I think the issue might be where the Dockstore CLI is trying to localize files, since the workflow works as expected with `java -jar /Applications/cromwell-85.jar run myco_simple.wdl -i inputs/myco_simple_local.json`


$ head -1 inputs/data/SAMEA3512769_ERR987753_1.fastq
@ERR987753.3080179 3080179 length=83

$ head -1 inputs/data/SAMEA3512769_ERR987753_2.fastq
@ERR987753.3080179 3080179 length=83

$ cat inputs/myco_simple_local.json 
{
  "myco.paired_decontaminated_fastq_sets": [["inputs/data/SAMEA3512769_ERR987753_1.fastq", "inputs/data/SAMEA3512769_ERR987753_2.fastq"]]
}

$ dockstore workflow launch --local-entry myco_simple.wdl --json inputs/myco_simple_local.json
```
Created temporary working directory at '/var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/1695846610368-0'
Using local file 'myco_simple.wdl' as primary descriptor
Creating directories for run of Dockstore launcher in current working directory: /Users/aofarrel/github/myco
Provisioning your input files to your local machine
Calling out to Cromwell to run your workflow
Executing: java -jar /Users/aofarrel/.dockstore/libraries/cromwell-84.jar run --inputs /var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/foo13916244835237115321json /Users/aofarrel/github/myco/myco_simple.wdl
[2023-09-27 13:30:14,88] [info] Running with database db.url = jdbc:hsqldb:mem:534a5edc-1313-4c92-bd25-41d45aac80d5;shutdown=false;hsqldb.tx=mvcc
[2023-09-27 13:30:16,90] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2023-09-27 13:30:16,91] [info] [RenameWorkflowOptionsInMetadata] 100%
[...]
[2023-09-27 13:30:28,14] [info] WorkflowManagerActor: Workflow 3347811f-2168-46c0-bc1a-ed5ce66221b5 failed (during ExecutingWorkflowState): cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1$$anon$1: Call input and runtime attributes evaluation failed for variant_call_each_sample:
Failed to evaluate input 'size_in' (reason 1 of 2): [Attempted 1 time(s)] - NoSuchFileException: /private/var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/1695846610368-0/inputs/data/SAMEA3512769_ERR987753_1.fastq
Failed to evaluate input 'size_in' (reason 2 of 2): [Attempted 1 time(s)] - NoSuchFileException: /private/var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/1695846610368-0/inputs/data/SAMEA3512769_ERR987753_2.fastq
Failed to evaluate input 'finalDiskSize' (reason 1 of 1): ValueEvaluator[IdentifierLookup]: No suitable input for 'size_in' amongst {crash_on_timeout, force, ssd, preempt, keep_bam, debug, tarball_bams_and_bais, cpu, timeout, mem_height, arg_debug, addldisk, retries, arg_keep_bam, crash_on_error, basename_reads, sample_name, arg_mem_height, diskType, arg_force, reads_files, memory}
[...]
```

$ tree /private/var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/1695846610368-0/
```
/private/var/folders/51/rhh2cl8x035f1rznw0g30c7m0000gn/T/1695846610368-0/
├── cromwell-executions
│   └── myco
│       └── 3347811f-2168-46c0-bc1a-ed5ce66221b5
└── cromwell-workflow-logs
```

**Comment by coverbeck** [comment]
@aofarrel I am able to successfully run the example shown on the [plugin page](https://github.com/dockstore/gs-plugin) -- although it fails uploading the results because the example JSON has `my_bucket` as the target, which I don't have permissions to, so that's expected. But it downloaded the file and the tool processed it.

So I'd say there's not a generic problem with the plugin.

For your problem, can you attach the workflow and test parameter json? Or point to where it is on Dockstore or GitHub? I tried finding it on Dockstore, but couldn't.

Thanks!

**Comment by aofarrel** [comment]
{{IN PROGRESS, WILL UPDATE THIS POST IN AN HOUR}}

I seem to be getting a different error now. The bucket is not requester pays (perhaps I accidentally set it as such in the earlier test).

```
[...]
[2024-01-17 11:20:54,47] [info] Assigned new job execution tokens to the following groups: 192fbb03: 1
[2024-01-17 11:20:54,58] [info] WorkflowManagerActor: Workflow 192fbb03-a945-4852-95c7-5987d63613bd failed (during ExecutingWorkflowState): cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1$$anon$1: Call input and runtime attributes evaluation failed for clean:
Failed to evaluate input 'disk_size' (reason 1 of 2): java.lang.IllegalArgumentException: Could not build the path "gs://ucsc-pathogen-genomics-public/tb/fq/gz/SAMEA3512769_ERR987753_1.fastq.gz". It may refer to a filesystem not supported by this instance of Cromwell. Supported filesystems are: HTTP, MacOSXFileSystem. Failures: 
HTTP: gs://ucsc-pathogen-genomics-public/tb/fq/gz/SAMEA3512769_ERR987753_1.fastq.gz does not have an http or https scheme (IllegalArgumentException)
MacOSXFileSystem: Cannot build a local path from gs://ucsc-pathogen-genomics-public/tb/fq/gz/SAMEA3512769_ERR987753_1.fastq.gz (RuntimeException)
 Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
Failed to evaluate input 'disk_size' (reason 2 of 2): java.lang.IllegalArgumentException: Could not build the path "gs://ucsc-pathogen-genomics-public/tb/fq/gz/SAMEA3512769_ERR987753_2.fastq.gz". It may refer to a filesystem not supported by this instance of Cromwell. Supported filesystems are: HTTP, MacOSXFileSystem. Failures: 
HTTP: gs://ucsc-pathogen-genomics-public/tb/fq/gz/SAMEA3512769_ERR987753_2.fastq.gz does not have an http or https scheme (IllegalArgumentException)
MacOSXFileSystem: Cannot build a local path from gs://ucsc-pathogen-genomics-public/tb/fq/gz/SAMEA3512769_ERR987753_2.fastq.gz (RuntimeException)
 Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems

[2024-01-17 11:20:59,38] [info] WorkflowManagerActor: Workflow actor for 192fbb03-a945-4852-95c7-5987d63613bd completed with status 'Failed'. The workflow will be removed from the workflow store.
[2024-01-17 11:21:00,24] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[...]
```

That seems to indicate the issue is how Cromwell is interpreting the file with regard to the WDL built-in `size()`. Ironically, I need to use size() to keep compatibility with Terra, and when running on Terra I am most definitely passing gs URIs into size(). Will try removing those and see what happens.

**Comment by coverbeck** [comment]
This because the CLI WDL provisioner will only provision parameters of type `File` and `Array<File>`. The workflow that is failing has an input parameter of type `Array<Array<File>>`, which we don't provision. I'm going to close this ticket and create a new one, as this one has evolved quite a bit.
