### ISSUE TITLE
Kronos + TitanCNA entry on Dockstore

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#850]
### Desired behaviour

The intent here is to add Kronos + TitanCNA as a tool for a demonstration of DNAStack integration, described with WDL (and optimally, CWL as well) ala https://dockstore.org/containers/quay.io/dockstore/phylowgs 

Unfortunately, we fell short of time after running across two issues.

Therefore I'm saving my work with Kronos + TitanCNA for a future second attempt. 

1. Kronos does have a Docker image `jtaghiyar/kronos`
2. The workflow can be checked out into the image when running interactively
```
apt-get update
apt-get install git
git clone https://github.com/dockstore/titan_workflow.git
cd titan_workflow/
apt-get install vim
wget https://dcc.icgc.org/api/v1/download?fn=/PCAWG/reference_data/data_for_testing/hg19.chr22.5x.normal.bam
mv download\?fn\=%2FPCAWG%2Freference_data%2Fdata_for_testing%2Fhg19.chr22.5x.normal.bam  hg19.chr22.5x.normal.bam
cp hg19.chr22.5x.normal.bam hg19.chr22.5x.normal2.bam
apt-get install r-base
kronos run -c /root/test/titan_workflow/components/ -e titan -i input.tsv -r test_run -s titan_setup.txt -W RES -y /root/test/titan_workflow/titan.yaml --no-prefix
```
3. The first puzzle is the setup of mutationseq which is mentioned in https://github.com/MO-BCCRC/titan_workflow but seems to be missing in the repo as reported in https://github.com/MO-BCCRC/titan_workflow/issues/3
4. This is the contents of the titan_setup.txt which is the equivalent of a SeqWare ini or a CWL params.yml
```
#section        key     value
__GENERAL__     python  /usr/local/bin/python
__GENERAL__     mutationseq     /path/to/mutationSeq_4.3.8
__GENERAL__     R       /usr/bin/R
__SHARED__      reference       /path/to/reference fasta file
__SHARED__      ld_library_path None
__SHARED__      pythonpath      pythonpath for the python 
__SHARED__      positions_file  dbsnp positions file 
__SHARED__      map     /path/to/mappability_wig
__SHARED__      gc      /path/to/gc_wig
__SHARED__      gene_sets_gtf   /path/to/hg19_gtf_pygenes_annotation
__SHARED__      interval_file   /root/test/titan_workflow/interval_file_titan.txt
__SHARED__      r_libs  /path/to/R_LIBS(for loading from  R libs from custom dir path,default:None)
__SHARED__      genome_type     NCBI(use UCSC if use UCSC reference)
__SHARED__      model   model_single_v4.0.2.npz
__SHARED__      museq_interval_file     /root/test/titan_workflow/interval_file_mutationseq_ucsc.txt
__SHARED__      y_threshold     20
__SHARED__      target_list     NULL(provide bed file with regions if running on exomes)
__SHARED__      chromosomes     ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X','Y']
```
5. This is the content of the input.tsv which stores more parameters
```
#sample_id      tumour_id       tumour_library_id       tumour  normal_id       normal_library_id       normal
SA123_A01234_SA123N_A01235      SA123   A01234  /root/test/titan_workflow/hg19.chr22.5x.normal.bam      SA123N  A01235  /path/to/SA123N.bam
SA223_A01234_SA223N_A01235      SA223   A01234  /root/test/titan_workflow/hg19.chr22.5x.normal2.bam     SA223N  A01235  /path/to/SA223N.bam
```
6. When attempting to run anyway, it seems like the workflow engine needs SGE 
```
root@603313e192c8:~/test/titan_workflow# kronos run -c /root/test/titan_workflow/components/ -e titan -i input.tsv -r test_run -s titan_setup.txt -W RES -y /root/test/titan_workflow/titan.yaml --no-prefix
2017-08-09 15:48:31,212 <<< kronos_2.0.4 started >>>
2017-08-09 15:48:31,212 running the pipeline ...
2017-08-09 15:48:31,398 making pipeline for SA223_A01234_SA223N_A01235 ...
2017-08-09 15:48:32,106 successfully completed.
2017-08-09 15:48:32,198 making pipeline for SA123_A01234_SA123N_A01235 ...
2017-08-09 15:48:32,926 successfully completed.
2017-08-09 15:48:32,927 successfully pasted pipelines.
2017-08-09 15:48:32,927 running the command: python /root/test/titan_workflow/titan.py -b drmaa -c /root/test/titan_workflow/components/ -d lib/lx24-amd64/libdrmaa.so -j 1 -n 1 -p python -w /root/test/tit
an_workflow -r 'test_run' -e 'titan'
2017-08-09 15:48:39,153 SA223_A01234_SA223N_A01235_titan pipeline finished with exit code 98
SA123_A01234_SA123N_A01235_titan pipeline finished with exit code 98

2017-08-09 15:48:39,153 failed to load DrmaaJobManager
Traceback (most recent call last):
  File "/root/test/titan_workflow/intermediate_pipeline_scripts/SA223_A01234_SA223N_A01235_titan.py", line 29, in <module>
    cjm = DrmaaJobManager(args.drmaa_library_path, rm.logs_dir, rm.outputs_dir, args.qsub_options)
  File "/usr/local/lib/python2.7/site-packages/kronos/job_manager.py", line 71, in __init__
    os.environ['DRMAA_LIBRARY_PATH'] = os.path.join(os.environ['SGE_ROOT'], drmaa_library_path)
  File "/usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SGE_ROOT'
    Job completed
Completed Task = task_0
failed to load DrmaaJobManager
Traceback (most recent call last):
  File "/root/test/titan_workflow/intermediate_pipeline_scripts/SA123_A01234_SA123N_A01235_titan.py", line 29, in <module>
    cjm = DrmaaJobManager(args.drmaa_library_path, rm.logs_dir, rm.outputs_dir, args.qsub_options)
  File "/usr/local/lib/python2.7/site-packages/kronos/job_manager.py", line 71, in __init__
    os.environ['DRMAA_LIBRARY_PATH'] = os.path.join(os.environ['SGE_ROOT'], drmaa_library_path)
  File "/usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SGE_ROOT'
    Job completed
Completed Task = task_1

2017-08-09 15:48:39,153 <<< kronos_2.0.4 finished >>>
``` 
This seems odd

Also attempting to join https://groups.google.com/forum/#!forum/kronos_pipeliner to get more insight into how Kronos works

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-500)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-500

**Comment by melainalegaspi** [comment]
revisit with DNASTACK ddep will likely need new workflow
